name: 03 - Workflow Runners

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: This job is running on Ubuntu runner."
              run: echo "Runner OS: $RUNNER_OS"